<robot name="car_base" xmlns:xacro="http://wiki.ros.org/xacro">

    <xacro:property name="footprint_radius" value="0.001" />
    <!-- 1.添加 base_footprint -->
    <link name="base_footprint">
        <visual>
            <geometry>
                <sphere radius="${footprint_radius}" />
            </geometry>
        </visual>
    </link>
    <!-- 2.添加底盘 -->
    <!--
        形状:圆柱
        半径:0.1m
        高度:0.08m
        离地间距:0.015m
    -->
    <xacro:property name="base_radius" value="0.1" />
    <xacro:property name="base_length" value="0.08" />
    <xacro:property name="base_mass" value="2" />
    <xacro:property name="distance_fg" value="0.015" />
    <xacro:property name="base_joint_z" value="${base_length/2 + distance_fg}" />
    <!-- 2-1.link -->
    <link name="base_link">
        <visual>
            <geometry>
                <cylinder radius="0.1" length="0.08" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="base_link_color">
                <color rgba="1 0 0 0.5" />
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.1" length="0.08" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <!-- 调用惯性矩阵函数 -->
        <xacro:cylinder_inertial_matrix m="${base_mass}" r="${base_radius}" h="${base_length}" />
    </link>
    <gazebo reference="base_link">
        <material>Gazebo/Yellow</material>
    </gazebo>
    <!-- 2-2.joint -->
    <joint name="link2footprint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <!-- 关节z上的设置 = 车体高度/2 + 离地间距 -->
        <origin xyz="0 0 0.055" rpy="0 0 0" />
    </joint>

    <!-- 3.添加驱动轮 -->
    <!-- 
        形状:圆柱
        半径:0.0325m
        长度:0.015m
    -->
    <!-- 属性 -->
    <xacro:property name="wheel_radius" value="0.0325" />
    <xacro:property name="wheel_length" value="0.015" />
    <xacro:property name="wheel_mass" value="1" />
    <xacro:property name="PI" value="3.1415927" />
    <!-- 注意:结果是负数 -->
    <xacro:property name="wheel_joint_z" value="${-base_length / 2 - distance_fg + wheel_radius}" />

    <!-- 
        wheel_name: left 或 right
        flag: 1 或 -1
    -->
    <xacro:macro name="wheel_func" params="wheel_name flag">
        <!-- 3-1.link -->
        <link name="${wheel_name}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${PI / 2} 0 0" />
                <material name="l_w_color">
                    <color rgba="0 0 0 1" />
                </material>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${PI / 2} 0 0" />
            </collision>
            <xacro:cylinder_inertial_matrix m="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}" />
        </link>
        <gazebo reference="${wheel_name}_wheel">
            <material>Gazebo/Red</material>
        </gazebo>

        <!-- 3-2.joint -->
        <joint name="${wheel_name}_wheel2base_link" type="continuous">
            <parent link="base_link" />
            <child link="${wheel_name}_wheel" />
            <!-- 
            x 无偏移
            y 车体半径
            z z = 车体高度/2+离地间距-车轮半径
        -->
            <origin xyz="0 ${0.1 * flag} ${wheel_joint_z}" rpy="0 0 0" />
            <axis xyz="0 1 0" />
        </joint>

    </xacro:macro>

    <xacro:wheel_func wheel_name="left" flag="1" />
    <xacro:wheel_func wheel_name="right" flag="-1" />

    <!-- 4.添加万向轮(支撑轮) -->
    <!-- 
        形状:球
        半径: 0.0075m
    -->

    <xacro:property name="uni_wheel_radius" value="0.0075" />
    <xacro:property name="uni_wheel_mass" value="0.01" />
    <!-- Z的偏移量=车体高度/2+离地间距-万向轮半径 -->
    <xacro:property name="uni_joint_z" value="${(base_length / 2 + distance_fg - uni_wheel_radius) *-1}" />

    <xacro:macro name="uni_wheel_func" params="uni_wheel_name flag">
        <!-- 4-1.link -->
        <link name="${uni_wheel_name}_wheel">
            <visual>
                <geometry>
                    <sphere radius="${uni_wheel_radius}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${uni_wheel_radius}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" /> 
            </collision>
            <xacro:sphere_inertial_matrix m="${uni_wheel_mass}" r="${uni_wheel_radius}" />
        </link>
        <gazebo reference="${uni_wheel_name}_wheel">
            <material>Gazebo/Red</material>
        </gazebo>
        <!-- 4-2.joint -->
        <joint name="${uni_wheel_name}_wheel2base_link" type="fixed">
            <parent link="base_link" />
            <child link="${uni_wheel_name}_wheel" />
            <origin xyz="${0.08 * flag} 0 ${uni_joint_z}" rpy="0 0 0" />
        </joint>

    </xacro:macro>

    <xacro:uni_wheel_func uni_wheel_name="front" flag="1" />
    <xacro:uni_wheel_func uni_wheel_name="back" flag="-1" />

</robot>