<robot name="car_laser" xmlns:xacro="http://wiki.ros.org/xacro">
    <!-- 雷达部件 -->
    <!-- 参数 -->
    <!-- 
        1.支架
            支架尺寸: 半径高度
            关节偏移量: x y z
        2.雷达
            雷达尺寸: 半径高度
            关节偏移量: x y z
    -->
    <xacro:property name="support_radius" value="0.01" />
    <xacro:property name="support_length" value="0.15" />
    <xacro:property name="laser_radius" value="0.03" />
    <xacro:property name="laser_length" value="0.05" />

    <xacro:property name="joint_support_x" value="0" />
    <xacro:property name="joint_support_y" value="0" />
    <!-- z = (车体高度+支架高度) /2 -->
    <xacro:property name="joint_support_z" value="${(base_length +support_length) / 2}" />

    <xacro:property name="joint_laser_x" value="0" />
    <xacro:property name="joint_laser_y" value="0" />
    <!-- z = (支架高度+雷达高度) /2 -->
    <xacro:property name="joint_laser_z" value="${(support_length + laser_length) / 2}" />

    <!-- 1.支架 -->
    <link name="support">
        <visual>
            <geometry>
                <cylinder radius="${support_radius}" length="${support_length}" />
            </geometry>
            <material name="black">
                <!-- <color rgba="0 0 0 1" /> -->
            </material>
        </visual>
    </link>
    
    <!-- 2.雷达 -->
    <link name="laser">
        <visual>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_length}" />
            </geometry>
            <material name="red">
                <color rgba="0.8 0.2 0 1" />
            </material>
        </visual>
    </link>
    <joint name="support2base_link" type="fixed">
        <parent link="base_link" />
        <child link="support" />
        <origin xyz="${joint_support_x} ${joint_support_y} ${joint_support_z}" rpy="0 0 0" />
    </joint>
    <joint name="laser2support" type="fixed">
        <parent link="support" />
        <child link="laser" />
        <origin xyz="${joint_laser_x} ${joint_laser_y} ${joint_laser_z}" rpy="0 0 0" />
    </joint>

</robot>